algoritmo "semnome"
// Função :
// Autor :
// Data : 10/09/2020
// Seção de Declarações 
var
n1, n2, soma : inteiro
inicio
// Seção de Comandos 
escreva("Digite o primeiro número inteiro: ")
leia(n1)
escreva("Digite o segundo número inteiro: ")
leia(n2)
soma <- n1 + n2
SE (soma > 20) ENTAO
   escreva("O valor é", soma + 8)
   SENAO
        escreva("O valor é", soma - 5)
FIMSE
fimalgoritmo
