algoritmo "semnome"
// Função :
// Autor :
// Data : 08/10/2020
// Seção de Declarações 
var
l : inteiro
nome : vetor[1..10] de caractere
inicio
// Seção de Comandos 
para l de 1 ate 10 faca
   escreva("Digite um nome na posição", l, ": ")
   leia(nome[l])
fimpara

escreval("Exibição dos nomes armazenados no vetor: ")
para l de 1 ate 10 faca
   escreval(nome[l])
fimpara
fimalgoritmo
