algoritmo "semnome"
// Função :
// Autor :
// Data : 08/10/2020
// Seção de Declarações 
var
l : inteiro
a : vetor[1..5] de inteiro
b : vetor[1..5] de inteiro
inicio
// Seção de Comandos 
para l de 1 ate 5 faca
   escreva("Elemento do vetor A[",l," ]: ")
   leia(a[l])
fimpara

 para l de 1 ate 5 faca
   escreva("Elemento do vetor B[",l," ]: ")
   leia(b[l])
fimpara

para l de 1 ate 5 faca
   escreval("Soma[",l," ] = ", a[l] + b[l])
fimpara
fimalgoritmo
